set -g status off
set -g pane-border-status top
set -g pane-border-format '#{?#{@panestra_cli_prompt}, #{@panestra_cli_prefix}#{@panestra_cli_prompt} ,#{?#{@panestra_cli_show_waiting}, Panestra CLI — Waiting for prompt ,}}'
set -g allow-rename off
set -g set-titles off
set -g exit-empty on
