#!/bin/sh

set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_root"

go_licenses_version=v2.0.1
expected_go_version=$(tr -d '[:space:]' < .go-version)
actual_go_version=$(go env GOVERSION)

if [ "$actual_go_version" != "go$expected_go_version" ]; then
  printf 'Go version mismatch: expected go%s, got %s\n' "$expected_go_version" "$actual_go_version" >&2
  exit 1
fi

go_notice_dir="third_party/go/go$expected_go_version"
for notice_file in LICENSE PATENTS; do
  if [ ! -f "$go_notice_dir/$notice_file" ]; then
    printf 'Missing Go notice for go%s: %s/%s\n' "$expected_go_version" "$go_notice_dir" "$notice_file" >&2
    exit 1
  fi
done

notice_tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/panestra-third-party-notices.XXXXXX")
generated_notice=$(mktemp "$repo_root/.THIRD_PARTY_NOTICES.XXXXXX")
cleanup() {
  rm -rf -- "$notice_tmp_dir"
  if [ -n "$generated_notice" ]; then
    rm -f -- "$generated_notice"
  fi
}
handle_signal() {
  exit 1
}
trap cleanup EXIT
trap handle_signal HUP INT TERM

generate_module_notices() {
  target_arch=$1
  output_file=$2

  GOOS=darwin GOARCH="$target_arch" \
    go run "github.com/google/go-licenses/v2@$go_licenses_version" \
      check ./cmd/panestra --ignore github.com/fru180/Panestra-cli
  GOOS=darwin GOARCH="$target_arch" \
    go run "github.com/google/go-licenses/v2@$go_licenses_version" \
      report ./cmd/panestra \
      --ignore github.com/fru180/Panestra-cli \
      --template scripts/third-party-notices.tpl > "$output_file"
}

arm_notices="$notice_tmp_dir/arm64"
intel_notices="$notice_tmp_dir/amd64"
generate_module_notices arm64 "$arm_notices"
generate_module_notices amd64 "$intel_notices"

if ! cmp -s "$arm_notices" "$intel_notices"; then
  printf 'Third-party notices differ between Darwin arm64 and amd64:\n' >&2
  diff -u "$arm_notices" "$intel_notices" >&2 || true
  exit 1
fi

{
  printf '%s\n\n' 'THIRD-PARTY SOFTWARE NOTICES'
  printf '%s\n' 'This file is generated by scripts/generate-third-party-notices.sh.'
  printf '%s\n\n' 'Do not edit it manually.'
  printf 'Go module notices were generated with github.com/google/go-licenses/v2 %s.\n\n' "$go_licenses_version"
  cat "$arm_notices"
  printf '%s\n' '================================================================================'
  printf '%s\n' 'Component: Go standard library and runtime'
  printf 'Version: go%s\n' "$expected_go_version"
  printf '%s\n' 'License: BSD-3-Clause'
  printf 'Source: https://github.com/golang/go/tree/go%s\n\n' "$expected_go_version"
  printf '%s\n\n' '[LICENSE]'
  cat "$go_notice_dir/LICENSE"
  printf '\n%s\n\n' '[PATENTS]'
  cat "$go_notice_dir/PATENTS"
} > "$generated_notice"

mv "$generated_notice" THIRD_PARTY_NOTICES
generated_notice=
